# templates/mongodb-service.yaml
{{- if .Values.use_self_mongo }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.mongodb.name }}
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.name }}
spec:
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image }}
        ports:
        - containerPort: 27017
          name: mongo
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongodb.secretName }}
                key: mongodb-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongodb.secretName }}
                key: mongodb-password
{{- end }}